#define TAPPING_TERM 300
#define TAPPING_TERM_PER_KEY
#define HOLD_ON_OTHER_KEY_PRESS
#define NO_ACTION_MACRO
#define NO_ACTION_FUNCTION

#define POINTING_DEVICE_RIGHT
#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_ROTATION_270
#define ANALOG_JOYSTICK_SPEED_REGULATOR 10

#undef STARTUP_SONG
#define STARTUP_SONG SONG(NO_SOUND)
